### ISSUE TITLE
Installation istruction ??

### ISSUE THREAD

**Issue by rwable** [Spuds/SMF-GeoIP#5]
How can I install this mod into my smf forum using package manager? Is there another way?
I do not know how to install it

**Comment by Spuds** [comment]
TBH I don't really recommend this package, it can be pretty difficult to install due to the various limits placed on sites by shared web hosting.   It requires quite a lot of memory to install, which is often not available, and then you have to try and do it manually.  

You can download it here: https://github.com/Spuds/SMF-GeoIP/archive/master.zip
